require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/page_appearances", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PageAppearance. As you add validations to PageAppearance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PageAppearance.create! valid_attributes
      get page_appearances_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      page_appearance = PageAppearance.create! valid_attributes
      get page_appearance_url(page_appearance)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_page_appearance_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      page_appearance = PageAppearance.create! valid_attributes
      get edit_page_appearance_url(page_appearance)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PageAppearance" do
        expect {
          post page_appearances_url, params: { page_appearance: valid_attributes }
        }.to change(PageAppearance, :count).by(1)
      end

      it "redirects to the created page_appearance" do
        post page_appearances_url, params: { page_appearance: valid_attributes }
        expect(response).to redirect_to(page_appearance_url(PageAppearance.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PageAppearance" do
        expect {
          post page_appearances_url, params: { page_appearance: invalid_attributes }
        }.to change(PageAppearance, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post page_appearances_url, params: { page_appearance: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested page_appearance" do
        page_appearance = PageAppearance.create! valid_attributes
        patch page_appearance_url(page_appearance), params: { page_appearance: new_attributes }
        page_appearance.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the page_appearance" do
        page_appearance = PageAppearance.create! valid_attributes
        patch page_appearance_url(page_appearance), params: { page_appearance: new_attributes }
        page_appearance.reload
        expect(response).to redirect_to(page_appearance_url(page_appearance))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        page_appearance = PageAppearance.create! valid_attributes
        patch page_appearance_url(page_appearance), params: { page_appearance: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested page_appearance" do
      page_appearance = PageAppearance.create! valid_attributes
      expect {
        delete page_appearance_url(page_appearance)
      }.to change(PageAppearance, :count).by(-1)
    end

    it "redirects to the page_appearances list" do
      page_appearance = PageAppearance.create! valid_attributes
      delete page_appearance_url(page_appearance)
      expect(response).to redirect_to(page_appearances_url)
    end
  end
end
